"""Generate ``ai_service/contracts/*.py`` from the committed JSON Schema in
``packages/contracts/*/schema/``.

ADR-0003's pipeline, Python end: Zod (authored) -> JSON Schema (generated and
committed by the contracts package) -> Pydantic (generated here, committed).
Phase 14 (docs/features/phase-14-ai-tool-calling/plan.md OD3) built it for
the four api-contracts shapes the Commerce API client consumes. Phase 15
(docs/features/phase-15-ai-ui-commands/plan.md section 9) adds two more
modules: the agent turn and its UI commands (``ui-commands``), and the
business intents (``agent-intents``).

Run from apps/ai-service:

    uv run python scripts/generate_contracts.py

tests/test_generated_contracts.py calls ``render()`` for every target and
fails if a committed module differs, so a stale or hand-edited model fails
the suite.

Only names are added to the schemas before generation (each ``title``): a
title changes a generated class name, never a constraint. The version of
datamodel-code-generator pinned in uv.lock makes the output deterministic.

One generator option maps types: ``string+date-time=string``. Without it,
``issuedAt`` becomes ``AwareDatetime`` carrying the contract's ``Z`` pattern,
and Pydantic cannot apply a pattern to a datetime, so every batch raised
``TypeError``. As a string, the field keeps the exact wire rule Zod enforces
(ISO-8601 UTC with ``Z``, ADR-0012 D9); JSON Schema's ``format`` is only an
annotation, and the schema itself is not edited.
"""

import copy
import json
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from datamodel_code_generator import generate
from datamodel_code_generator.enums import DataModelType, InputFileType
from datamodel_code_generator.format import Formatter, PythonVersion

SERVICE_ROOT = Path(__file__).resolve().parents[1]
CONTRACTS_ROOT = SERVICE_ROOT.parents[1] / "packages/contracts"
CONTRACTS_DIR = SERVICE_ROOT / "ai_service/contracts"

# api-contracts (Phase 14). These three names predate the other targets and
# keep their meaning: tests/test_tool_schemas.py reads SCHEMA_DIR.
SCHEMA_DIR = CONTRACTS_ROOT / "api-contracts/schema"
OUTPUT = CONTRACTS_DIR / "api_contracts.py"

# Class name -> committed schema file. The first entry becomes the root
# document and the others its $defs: a document of $defs alone would also
# generate a placeholder root model.
SCHEMAS = {
    "MenuResponse": "menu.v1.json",
    "CartResponse": "cart.v1.json",
    "AddCartItemRequest": "cart-add-item-request.v1.json",
    "UpdateCartItemRequest": "cart-update-item-request.v1.json",
}

# Nested object -> the Zod schema's own name (menuCategorySchema,
# menuItemSchema, cartLineSchema), instead of the generator's Item/Item1.
NESTED_TITLES: dict[tuple[str, ...], str] = {
    ("MenuResponse", "categories"): "MenuCategory",
    ("MenuResponse", "categories", "items"): "MenuItem",
    ("CartResponse", "items"): "CartLine",
}

UI_COMMANDS_SCHEMA_DIR = CONTRACTS_ROOT / "ui-commands/schema"
AGENT_INTENTS_SCHEMA_DIR = CONTRACTS_ROOT / "agent-intents/schema"


def _header(source: str) -> str:
    return f"""\
# GENERATED by scripts/generate_contracts.py from
# {source}. Do not edit by hand:
# change the Zod source, rebuild its JSON Schema, then rerun
#   uv run python scripts/generate_contracts.py
# tests/test_generated_contracts.py fails if this file drifts (ADR-0003)."""


def _load(schema_dir: Path, file_name: str) -> dict[str, Any]:
    schema: dict[str, Any] = json.loads((schema_dir / file_name).read_text())
    # The combined document has one $schema; nested $id values would make
    # each definition its own resolution scope.
    schema.pop("$schema", None)
    schema.pop("$id", None)
    return schema


def _array_item(schema: dict[str, Any], prop: str) -> dict[str, Any]:
    item: dict[str, Any] = schema["properties"][prop]["items"]
    return item


def _title_union_branches(union: dict[str, Any]) -> None:
    """Name each ``oneOf`` branch after its ``type`` discriminator, which is
    the Zod schema's own command or intent name (``ShowMenuCategory``,
    ``AddItemToCart``), instead of the generator's Model1, Model2."""
    for branch in union["oneOf"]:
        branch["title"] = branch["properties"]["type"]["const"]


def _api_contracts_schema() -> dict[str, Any]:
    definitions = {name: _load(SCHEMA_DIR, file) for name, file in SCHEMAS.items()}
    for name, schema in definitions.items():
        schema["title"] = name
    for (name, *path), title in NESTED_TITLES.items():
        node = definitions[name]
        for prop in path:
            node = _array_item(node, prop)
        node["title"] = title
    root_name, *other_names = SCHEMAS
    root = copy.deepcopy(definitions[root_name])
    root["$defs"] = {name: definitions[name] for name in other_names}
    return root


def _ui_commands_schema() -> dict[str, Any]:
    """The agent turn (Phase 15): the response as root, the request in
    $defs. The UI command batch and its commands are nested in the response,
    so they are generated from it rather than from ui-command.v1.json, which
    holds the same batch schema and would generate it twice."""
    response = _load(UI_COMMANDS_SCHEMA_DIR, "agent-turn-response.v1.json")
    request = _load(UI_COMMANDS_SCHEMA_DIR, "agent-turn-request.v1.json")
    response["title"] = "AgentTurnResponse"
    request["title"] = "AgentTurnRequest"
    batch = response["properties"]["uiCommands"]
    batch["title"] = "UiCommandBatch"
    command = _array_item(batch, "commands")
    command["title"] = "UiCommand"
    _title_union_branches(command)
    response["$defs"] = {"AgentTurnRequest": request}
    return response


def _agent_intents_schema() -> dict[str, Any]:
    """The intent union only (Phase 15 plan.md section 5). The request
    envelope around it (idempotencyKey, ...) has no endpoint that accepts it,
    so nothing in this service builds one, and it is not generated."""
    envelope = _load(AGENT_INTENTS_SCHEMA_DIR, "agent-intent.v1.json")
    intent: dict[str, Any] = envelope["properties"]["intent"]
    intent["title"] = "AgentIntent"
    _title_union_branches(intent)
    return intent


@dataclass(frozen=True)
class Target:
    output: Path
    # Committed schema files this module is generated from.
    sources: tuple[Path, ...]
    header: str
    build: Callable[[], dict[str, Any]]


TARGETS: dict[str, Target] = {
    "api_contracts": Target(
        output=OUTPUT,
        sources=tuple(SCHEMA_DIR / file for file in SCHEMAS.values()),
        header=_header("packages/contracts/api-contracts/schema/*.v1.json"),
        build=_api_contracts_schema,
    ),
    "ui_commands": Target(
        output=CONTRACTS_DIR / "ui_commands.py",
        sources=(
            UI_COMMANDS_SCHEMA_DIR / "agent-turn-response.v1.json",
            UI_COMMANDS_SCHEMA_DIR / "agent-turn-request.v1.json",
        ),
        header=_header("packages/contracts/ui-commands/schema/agent-turn-*.v1.json"),
        build=_ui_commands_schema,
    ),
    "agent_intents": Target(
        output=CONTRACTS_DIR / "agent_intents.py",
        sources=(AGENT_INTENTS_SCHEMA_DIR / "agent-intent.v1.json",),
        header=_header(
            "packages/contracts/agent-intents/schema/agent-intent.v1.json\n"
            "# (the intent union only, not its request envelope)"
        ),
        build=_agent_intents_schema,
    ),
}


def render(target: Target) -> str:
    output = generate(
        target.build(),
        input_file_type=InputFileType.JsonSchema,
        output_model_type=DataModelType.PydanticV2BaseModel,
        target_python_version=PythonVersion.PY_312,
        # Strict, like every Zod source object (ADR-0012).
        extra_fields="forbid",
        field_constraints=True,
        use_annotated=True,
        use_standard_collections=True,
        use_union_operator=True,
        use_title_as_name=True,
        disable_timestamp=True,
        # See the module docstring: keeps issuedAt a pattern-checked string.
        type_mappings=["string+date-time=string"],
        custom_file_header=target.header,
        formatters=[Formatter.RUFF_FORMAT, Formatter.RUFF_CHECK],
    )
    assert isinstance(output, str)  # noqa: S101 - one module in, one string out
    return output if output.endswith("\n") else output + "\n"


def main() -> None:
    for target in TARGETS.values():
        target.output.write_text(render(target))
        print(f"wrote {target.output.relative_to(SERVICE_ROOT)}")


if __name__ == "__main__":
    main()
