"""Generate ``ai_service/contracts/api_contracts.py`` from the committed JSON
Schema in ``packages/contracts/api-contracts/schema/``.

ADR-0003's pipeline, Python end: Zod (authored) -> JSON Schema (generated and
committed by the contracts package) -> Pydantic (generated here, committed).
Phase 14 (docs/features/phase-14-ai-tool-calling/plan.md OD3) builds it for
the four shapes the Commerce API client consumes, and nothing else.

Run from apps/ai-service:

    uv run python scripts/generate_contracts.py

tests/test_generated_contracts.py calls ``render()`` and fails if the
committed module differs, so a stale or hand-edited model fails the suite.

Only names are added to the schemas before generation (each ``title``): a
title changes a generated class name, never a constraint. The version of
datamodel-code-generator pinned in uv.lock makes the output deterministic.
"""

import copy
import json
from pathlib import Path
from typing import Any

from datamodel_code_generator import generate
from datamodel_code_generator.enums import DataModelType, InputFileType
from datamodel_code_generator.format import Formatter, PythonVersion

SERVICE_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = SERVICE_ROOT.parents[1] / "packages/contracts/api-contracts/schema"
OUTPUT = SERVICE_ROOT / "ai_service/contracts/api_contracts.py"

# Class name -> committed schema file. The first entry becomes the root
# document and the others its $defs: a document of $defs alone would also
# generate a placeholder root model.
SCHEMAS = {
    "MenuResponse": "menu.v1.json",
    "CartResponse": "cart.v1.json",
    "AddCartItemRequest": "cart-add-item-request.v1.json",
    "UpdateCartItemRequest": "cart-update-item-request.v1.json",
}

# Nested object -> the Zod schema's own name (menuCategorySchema,
# menuItemSchema, cartLineSchema), instead of the generator's Item/Item1.
NESTED_TITLES: dict[tuple[str, ...], str] = {
    ("MenuResponse", "categories"): "MenuCategory",
    ("MenuResponse", "categories", "items"): "MenuItem",
    ("CartResponse", "items"): "CartLine",
}

HEADER = """\
# GENERATED by scripts/generate_contracts.py from
# packages/contracts/api-contracts/schema/*.v1.json. Do not edit by hand:
# change the Zod source, rebuild its JSON Schema, then rerun
#   uv run python scripts/generate_contracts.py
# tests/test_generated_contracts.py fails if this file drifts (ADR-0003)."""


def _load(file_name: str) -> dict[str, Any]:
    schema: dict[str, Any] = json.loads((SCHEMA_DIR / file_name).read_text())
    # The combined document has one $schema; nested $id values would make
    # each definition its own resolution scope.
    schema.pop("$schema", None)
    schema.pop("$id", None)
    return schema


def _array_item(schema: dict[str, Any], prop: str) -> dict[str, Any]:
    item: dict[str, Any] = schema["properties"][prop]["items"]
    return item


def _combined_schema() -> dict[str, Any]:
    definitions = {name: _load(file) for name, file in SCHEMAS.items()}
    for name, schema in definitions.items():
        schema["title"] = name
    for (name, *path), title in NESTED_TITLES.items():
        node = definitions[name]
        for prop in path:
            node = _array_item(node, prop)
        node["title"] = title
    root_name, *other_names = SCHEMAS
    root = copy.deepcopy(definitions[root_name])
    root["$defs"] = {name: definitions[name] for name in other_names}
    return root


def render() -> str:
    output = generate(
        _combined_schema(),
        input_file_type=InputFileType.JsonSchema,
        output_model_type=DataModelType.PydanticV2BaseModel,
        target_python_version=PythonVersion.PY_312,
        # Strict, like every Zod source object (ADR-0012).
        extra_fields="forbid",
        field_constraints=True,
        use_annotated=True,
        use_standard_collections=True,
        use_union_operator=True,
        use_title_as_name=True,
        disable_timestamp=True,
        custom_file_header=HEADER,
        formatters=[Formatter.RUFF_FORMAT, Formatter.RUFF_CHECK],
    )
    assert isinstance(output, str)  # noqa: S101 - one module in, one string out
    return output if output.endswith("\n") else output + "\n"


def main() -> None:
    OUTPUT.write_text(render())
    print(f"wrote {OUTPUT.relative_to(SERVICE_ROOT)}")


if __name__ == "__main__":
    main()
