# GENERATED by scripts/generate_contracts.py from
# packages/contracts/agent-intents/schema/agent-intent.v1.json
# (the intent union only, not its request envelope). Do not edit by hand:
# change the Zod source, rebuild its JSON Schema, then rerun
#   uv run python scripts/generate_contracts.py
# tests/test_generated_contracts.py fails if this file drifts (ADR-0003).

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AddItemToCart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["AddItemToCart"]
    itemId: Annotated[
        str, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]
    quantity: Annotated[int, Field(ge=1, le=99)]


class RemoveItemFromCart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["RemoveItemFromCart"]
    itemId: Annotated[
        str, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]


class SetCartItemQuantity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["SetCartItemQuantity"]
    itemId: Annotated[
        str, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]
    quantity: Annotated[int, Field(ge=1, le=99)]


class AgentIntent(RootModel[AddItemToCart | RemoveItemFromCart | SetCartItemQuantity]):
    root: Annotated[
        AddItemToCart | RemoveItemFromCart | SetCartItemQuantity,
        Field(title="AgentIntent"),
    ]
