# GENERATED by scripts/generate_contracts.py from
# packages/contracts/api-contracts/schema/*.v1.json. Do not edit by hand:
# change the Zod source, rebuild its JSON Schema, then rerun
#   uv run python scripts/generate_contracts.py
# tests/test_generated_contracts.py fails if this file drifts (ADR-0003).

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class DietaryTag(RootModel[str]):
    root: Annotated[
        str, Field(max_length=32, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]


class Allergen(RootModel[str]):
    root: Annotated[
        str, Field(max_length=32, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]


class MenuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[
        str, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]
    categoryId: Annotated[
        str, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]
    name: Annotated[str, Field(max_length=80, min_length=1)]
    description: Annotated[str, Field(max_length=200, min_length=1)]
    longDescription: Annotated[str, Field(max_length=1000, min_length=1)]
    priceCents: Annotated[int, Field(ge=0, le=9007199254740991)]
    available: bool
    dietaryTags: Annotated[list[DietaryTag], Field(max_length=10)]
    allergens: Annotated[list[Allergen], Field(max_length=20)]
    calories: Annotated[int, Field(ge=0, le=9007199254740991)]


class MenuCategory(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[
        str, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]
    name: Annotated[str, Field(max_length=80, min_length=1)]
    items: list[MenuItem]


class MenuResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    categories: list[MenuCategory]


class CartLine(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    itemId: Annotated[
        str, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]
    name: Annotated[str, Field(max_length=80, min_length=1)]
    unitPriceCents: Annotated[int, Field(ge=0, le=9007199254740991)]
    quantity: Annotated[int, Field(ge=1, le=99)]
    lineSubtotalCents: Annotated[int, Field(ge=0, le=9007199254740991)]
    available: bool


class CartResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[CartLine]
    itemCount: Annotated[int, Field(ge=0, le=9007199254740991)]
    subtotalCents: Annotated[int, Field(ge=0, le=9007199254740991)]


class AddCartItemRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    itemId: Annotated[
        str, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]
    quantity: Annotated[int, Field(ge=1, le=99)]


class UpdateCartItemRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    quantity: Annotated[int, Field(ge=1, le=99)]
