# GENERATED by scripts/generate_contracts.py from
# packages/contracts/ui-commands/schema/agent-turn-*.v1.json. Do not edit by hand:
# change the Zod source, rebuild its JSON Schema, then rerun
#   uv run python scripts/generate_contracts.py
# tests/test_generated_contracts.py fails if this file drifts (ADR-0003).

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ShowMenuCategory(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["ShowMenuCategory"]
    categoryId: Annotated[
        str, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]


class HighlightItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["HighlightItem"]
    itemId: Annotated[
        str, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]


class OpenCartPanel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["OpenCartPanel"]
    open: bool


class ShowItemDetail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["ShowItemDetail"]
    itemId: Annotated[
        str, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")
    ]


class SearchMenu(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["SearchMenu"]
    query: Annotated[str, Field(max_length=200)]


class UiCommand(
    RootModel[
        ShowMenuCategory | HighlightItem | OpenCartPanel | ShowItemDetail | SearchMenu
    ]
):
    root: Annotated[
        ShowMenuCategory | HighlightItem | OpenCartPanel | ShowItemDetail | SearchMenu,
        Field(title="UiCommand"),
    ]


class UiCommandBatch(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contractVersion: Literal[1]
    correlationId: Annotated[str, Field(max_length=64, min_length=1)]
    issuedAt: Annotated[
        str,
        Field(
            pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"
        ),
    ]
    commands: Annotated[list[UiCommand], Field(max_length=10, min_length=1)]


class AgentTurnResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reply: Annotated[str, Field(max_length=4000, min_length=1)]
    uiCommands: Annotated[UiCommandBatch | None, Field(title="UiCommandBatch")] = None


class AgentTurnRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: Annotated[str, Field(max_length=2000, min_length=1, pattern="\\S")]
