import type { MenuCategory, MenuItem } from "../domain/menu.types";

// The menu `db:seed` loads — a generic quick-service menu for the
// McDelivery-style UI (docs/features/mcdelivery-redesign/plan.md, Phase 2,
// scope change option A). Original names and copy; no brand's products.
// Prices are in paise (₹1 = 100), like every other *Cents value.
//
// MENU_SEED (menu.seed.ts) stays the DB-free test menu that the in-memory
// adapter serves and the existing tests assert; this one is only loaded
// into a database. Images are same-origin paths apps/web serves from
// public/menu/.

type ItemInput = Omit<MenuItem, "id" | "categoryId" | "available"> & {
  readonly id: string;
  readonly available?: boolean;
};

function category(
  id: string,
  name: string,
  imageUrl: string,
  items: readonly ItemInput[],
): MenuCategory {
  return {
    id,
    name,
    imageUrl,
    items: items.map((item) => ({ ...item, categoryId: id, available: item.available ?? true })),
  };
}

const VEG = ["vegetarian"] as const;

export const DEMO_MENU_SEED: readonly MenuCategory[] = [
  category("breakfast", "Breakfast & Mornings", "/menu/breakfast.svg", [
    {
      id: "egg-muffin",
      name: "Egg & Cheese Muffin",
      description: "Toasted muffin, folded egg, melted cheese.",
      longDescription:
        "A toasted English muffin with a freshly folded egg and a slice of " +
        "melted cheese. Simple, warm and ready in minutes.",
      priceCents: 12900,
      dietaryTags: [],
      allergens: ["gluten", "dairy", "egg"],
      calories: 290,
      imageUrl: "/menu/breakfast.svg",
      weightGrams: 125,
      badge: "bestseller",
      featured: ["popular"],
    },
    {
      id: "veg-breakfast-muffin",
      name: "Veggie Breakfast Muffin",
      description: "Spiced veg patty, cheese, toasted muffin.",
      longDescription:
        "A crisp spiced vegetable patty with a slice of cheese in a toasted " +
        "English muffin.",
      priceCents: 11900,
      dietaryTags: [...VEG],
      allergens: ["gluten", "dairy"],
      calories: 310,
      imageUrl: "/menu/breakfast.svg",
      weightGrams: 130,
    },
    {
      id: "hash-brown",
      name: "Crispy Hash Brown",
      description: "Golden shredded potato, crisp outside.",
      longDescription: "Shredded potato, pressed and fried until golden and crisp.",
      priceCents: 6900,
      dietaryTags: [...VEG],
      allergens: [],
      calories: 150,
      imageUrl: "/menu/fries.svg",
      weightGrams: 55,
      badge: "value",
      featured: ["deal"],
    },
    {
      id: "pancake-stack",
      name: "Pancake Stack",
      description: "Three fluffy pancakes with maple-style syrup.",
      longDescription:
        "Three fluffy pancakes served with butter and a maple-style syrup.",
      priceCents: 14900,
      dietaryTags: [...VEG],
      allergens: ["gluten", "dairy", "egg"],
      calories: 520,
      imageUrl: "/menu/dessert.svg",
      weightGrams: 180,
    },
  ]),
  category("burgers-wraps", "Burgers & Wraps", "/menu/burger.svg", [
    {
      id: "classic-veg-burger",
      name: "Classic Veg Burger",
      description: "Spiced potato-pea patty, lettuce, creamy sauce.",
      longDescription:
        "A spiced potato and pea patty with crisp lettuce and a creamy house " +
        "sauce in a soft sesame bun.",
      priceCents: 6900,
      dietaryTags: [...VEG],
      allergens: ["gluten", "sesame", "dairy"],
      calories: 340,
      imageUrl: "/menu/burger.svg",
      weightGrams: 145,
      badge: "value",
      featured: ["popular", "deal"],
    },
    {
      id: "paneer-crunch-burger",
      name: "Paneer Crunch Burger",
      description: "Crumbed paneer slab, tangy sauce, onions.",
      longDescription:
        "A thick slab of crumbed paneer, fried crisp, with tangy tomato sauce " +
        "and sliced onions.",
      priceCents: 18900,
      dietaryTags: [...VEG],
      allergens: ["gluten", "dairy", "sesame"],
      calories: 520,
      imageUrl: "/menu/burger.svg",
      weightGrams: 190,
      badge: "bestseller",
      featured: ["popular"],
    },
    {
      id: "crispy-chicken-burger",
      name: "Crispy Chicken Burger",
      description: "Crunchy chicken fillet, lettuce, mayo.",
      longDescription:
        "A crunchy seasoned chicken fillet with shredded lettuce and mayo in " +
        "a toasted bun.",
      priceCents: 16900,
      dietaryTags: [],
      allergens: ["gluten", "egg", "sesame"],
      calories: 480,
      imageUrl: "/menu/burger.svg",
      weightGrams: 175,
      featured: ["popular"],
    },
    {
      id: "double-chicken-burger",
      name: "Double Chicken Stack",
      description: "Two grilled chicken patties, cheese, pickles.",
      longDescription:
        "Two flame-grilled chicken patties with cheese, pickles and a smoky " +
        "sauce.",
      priceCents: 23900,
      dietaryTags: [],
      allergens: ["gluten", "dairy", "sesame"],
      calories: 640,
      imageUrl: "/menu/burger.svg",
      weightGrams: 230,
      badge: "new",
      featured: ["new-launch"],
    },
    {
      id: "spicy-veg-wrap",
      name: "Spicy Veg Wrap",
      description: "Crispy veg strips, salad, spicy sauce, soft wrap.",
      longDescription:
        "Crispy vegetable strips with fresh salad and a spicy sauce, rolled " +
        "in a soft flatbread.",
      priceCents: 15900,
      dietaryTags: [...VEG],
      allergens: ["gluten", "dairy"],
      calories: 450,
      imageUrl: "/menu/wrap.svg",
      weightGrams: 200,
      badge: "new",
      featured: ["new-launch"],
    },
    {
      id: "grilled-chicken-wrap",
      name: "Grilled Chicken Wrap",
      description: "Grilled chicken, peppers, mint mayo.",
      longDescription:
        "Grilled chicken strips with sautéed peppers and a cooling mint mayo " +
        "in a warm flatbread.",
      priceCents: 19900,
      dietaryTags: [],
      allergens: ["gluten", "egg"],
      calories: 490,
      imageUrl: "/menu/wrap.svg",
      weightGrams: 210,
    },
  ]),
  category("fried-chicken", "Fried Chicken & Wings", "/menu/chicken.svg", [
    {
      id: "chicken-strips-3",
      name: "Chicken Strips (3 pc)",
      description: "Three crunchy chicken strips with a dip.",
      longDescription: "Three crunchy, seasoned chicken strips with a dip of your choice.",
      priceCents: 15900,
      dietaryTags: [],
      allergens: ["gluten", "egg"],
      calories: 380,
      imageUrl: "/menu/chicken.svg",
      weightGrams: 120,
      featured: ["popular"],
    },
    {
      id: "chicken-bites-9",
      name: "Chicken Bites (9 pc)",
      description: "Bite-sized crispy chicken for sharing.",
      longDescription: "Nine bite-sized pieces of crispy chicken, good for sharing.",
      priceCents: 17900,
      dietaryTags: [],
      allergens: ["gluten"],
      calories: 420,
      imageUrl: "/menu/chicken.svg",
      weightGrams: 150,
      badge: "value",
      featured: ["deal"],
    },
    {
      id: "hot-wings-4",
      name: "Hot Wings (4 pc)",
      description: "Spicy, crispy chicken wings.",
      longDescription: "Four chicken wings with a spicy, crispy coating.",
      priceCents: 19900,
      dietaryTags: [],
      allergens: ["gluten"],
      calories: 400,
      imageUrl: "/menu/chicken.svg",
      weightGrams: 160,
    },
  ]),
  category("fries-sides", "Fries & Sides", "/menu/fries.svg", [
    {
      id: "fries-medium",
      name: "Fries (Medium)",
      description: "Golden, salted fries.",
      longDescription: "Thin-cut potato fries, fried golden and lightly salted.",
      priceCents: 10900,
      dietaryTags: [...VEG],
      allergens: [],
      calories: 320,
      imageUrl: "/menu/fries.svg",
      weightGrams: 110,
      badge: "bestseller",
      featured: ["popular"],
    },
    {
      id: "peri-peri-fries",
      name: "Peri Peri Fries",
      description: "Fries tossed in a spicy peri peri mix.",
      longDescription: "Our medium fries tossed in a tangy, spicy peri peri seasoning.",
      priceCents: 12900,
      dietaryTags: [...VEG],
      allergens: [],
      calories: 340,
      imageUrl: "/menu/fries.svg",
      weightGrams: 115,
    },
    {
      id: "veg-nuggets-6",
      name: "Veg Nuggets (6 pc)",
      description: "Crispy vegetable nuggets with a dip.",
      longDescription: "Six crispy vegetable nuggets served with a tangy dip.",
      priceCents: 11900,
      dietaryTags: [...VEG],
      allergens: ["gluten"],
      calories: 290,
      imageUrl: "/menu/chicken.svg",
      weightGrams: 100,
    },
    {
      id: "corn-cup",
      name: "Buttered Corn Cup",
      description: "Sweet corn with butter and a pinch of spice.",
      longDescription: "Steamed sweet corn tossed with butter and a light spice mix.",
      priceCents: 8900,
      dietaryTags: [...VEG],
      allergens: ["dairy"],
      calories: 160,
      imageUrl: "/menu/salad.svg",
      weightGrams: 120,
      badge: "value",
      featured: ["deal"],
    },
  ]),
  category("meals", "Value Meals", "/menu/meal.svg", [
    {
      id: "veg-burger-meal",
      name: "Veg Burger Meal",
      description: "Classic Veg Burger, medium fries and a drink.",
      longDescription:
        "A Classic Veg Burger with medium fries and a medium soft drink.",
      priceCents: 24900,
      dietaryTags: [...VEG],
      allergens: ["gluten", "sesame", "dairy"],
      calories: 820,
      imageUrl: "/menu/meal.svg",
      badge: "value",
      featured: ["deal", "popular"],
    },
    {
      id: "chicken-burger-meal",
      name: "Chicken Burger Meal",
      description: "Crispy Chicken Burger, medium fries and a drink.",
      longDescription:
        "A Crispy Chicken Burger with medium fries and a medium soft drink.",
      priceCents: 32900,
      dietaryTags: [],
      allergens: ["gluten", "egg", "sesame"],
      calories: 960,
      imageUrl: "/menu/meal.svg",
      featured: ["deal"],
    },
    {
      id: "sharing-box",
      name: "Sharing Box for 2",
      description: "Two burgers, two fries, 9 chicken bites, two drinks.",
      longDescription:
        "Two Classic Veg or Crispy Chicken Burgers, two medium fries, nine " +
        "chicken bites and two medium drinks.",
      priceCents: 69900,
      dietaryTags: [],
      allergens: ["gluten", "egg", "sesame", "dairy"],
      calories: 2400,
      imageUrl: "/menu/meal.svg",
      badge: "new",
      featured: ["new-launch", "deal"],
    },
  ]),
  category("beverages", "Cold Drinks & Shakes", "/menu/drink.svg", [
    {
      id: "soft-drink-medium",
      name: "Soft Drink (Medium)",
      description: "Chilled fizzy drink, your choice of flavour.",
      longDescription: "A medium chilled soft drink in the flavour of your choice.",
      priceCents: 8900,
      dietaryTags: [...VEG],
      allergens: [],
      calories: 150,
      imageUrl: "/menu/drink.svg",
      weightGrams: 400,
      featured: ["popular"],
    },
    {
      id: "iced-lemon-tea",
      name: "Iced Lemon Tea",
      description: "Brewed tea, lemon, served over ice.",
      longDescription: "Freshly brewed black tea with lemon, lightly sweetened, over ice.",
      priceCents: 9900,
      dietaryTags: [...VEG],
      allergens: [],
      calories: 90,
      imageUrl: "/menu/drink.svg",
      weightGrams: 350,
    },
    {
      id: "chocolate-shake",
      name: "Chocolate Shake",
      description: "Thick, creamy chocolate shake.",
      longDescription: "A thick, creamy milkshake blended with rich chocolate.",
      priceCents: 14900,
      dietaryTags: [...VEG],
      allergens: ["dairy"],
      calories: 420,
      imageUrl: "/menu/drink.svg",
      weightGrams: 350,
      badge: "bestseller",
    },
    {
      id: "mango-smoothie",
      name: "Mango Smoothie",
      description: "Mango, yoghurt, blended cold.",
      longDescription: "Ripe mango blended with yoghurt, served cold.",
      priceCents: 15900,
      dietaryTags: [...VEG],
      allergens: ["dairy"],
      calories: 280,
      imageUrl: "/menu/drink.svg",
      weightGrams: 350,
      badge: "new",
      featured: ["new-launch"],
      available: false,
    },
  ]),
  category("coffee", "Coffee & Tea", "/menu/coffee.svg", [
    {
      id: "cappuccino",
      name: "Cappuccino",
      description: "Espresso, steamed milk, thick foam.",
      longDescription: "A double shot of espresso with steamed milk and a thick layer of foam.",
      priceCents: 13900,
      dietaryTags: [...VEG],
      allergens: ["dairy"],
      calories: 130,
      imageUrl: "/menu/coffee.svg",
      weightGrams: 240,
    },
    {
      id: "masala-chai",
      name: "Masala Chai",
      description: "Spiced milk tea, brewed strong.",
      longDescription: "Black tea brewed strong with milk, ginger and warming spices.",
      priceCents: 7900,
      dietaryTags: [...VEG],
      allergens: ["dairy"],
      calories: 110,
      imageUrl: "/menu/coffee.svg",
      weightGrams: 200,
      badge: "value",
      featured: ["deal"],
    },
    {
      id: "cold-coffee",
      name: "Cold Coffee",
      description: "Chilled coffee, milk, ice.",
      longDescription: "Chilled brewed coffee blended with milk and ice.",
      priceCents: 14900,
      dietaryTags: [...VEG],
      allergens: ["dairy"],
      calories: 210,
      imageUrl: "/menu/coffee.svg",
      weightGrams: 300,
      featured: ["popular"],
    },
  ]),
  category("sweets", "Desserts", "/menu/dessert.svg", [
    {
      id: "soft-serve-cone",
      name: "Soft Serve Cone",
      description: "Vanilla soft serve in a crisp cone.",
      longDescription: "Creamy vanilla soft serve swirled into a crisp wafer cone.",
      priceCents: 4900,
      dietaryTags: [...VEG],
      allergens: ["dairy", "gluten"],
      calories: 170,
      imageUrl: "/menu/dessert.svg",
      weightGrams: 90,
      badge: "value",
      featured: ["deal", "popular"],
    },
    {
      id: "chocolate-sundae",
      name: "Chocolate Sundae",
      description: "Soft serve, warm chocolate sauce.",
      longDescription: "Vanilla soft serve topped with warm chocolate sauce.",
      priceCents: 8900,
      dietaryTags: [...VEG],
      allergens: ["dairy"],
      calories: 290,
      imageUrl: "/menu/dessert.svg",
      weightGrams: 150,
    },
    {
      id: "brownie",
      name: "Fudge Brownie",
      description: "Dense chocolate brownie, served warm.",
      longDescription: "A dense, fudgy chocolate brownie, warmed before serving.",
      priceCents: 9900,
      dietaryTags: [...VEG],
      allergens: ["gluten", "dairy", "egg"],
      calories: 360,
      imageUrl: "/menu/dessert.svg",
      weightGrams: 80,
      badge: "new",
      featured: ["new-launch"],
    },
  ]),
];
